#pragma once

#include "rule.h"
#include <Windows.h>
#include <iostream>
#include <string>

#define DRIVER_OBJECT_SYM_NAME "\\\\.\\wfp_demo"

#define ADD_RULE CTL_CODE(FILE_DEVICE_UNKNOWN, 0x801, METHOD_BUFFERED, FILE_READ_DATA|FILE_WRITE_DATA)

#define CLEAR_RULE_LIST CTL_CODE(FILE_DEVICE_UNKNOWN, 0x802, METHOD_BUFFERED, FILE_READ_DATA|FILE_WRITE_DATA)

#define GET_RULE_LIST CTL_CODE(FILE_DEVICE_UNKNOWN, 0x803, METHOD_BUFFERED, FILE_READ_DATA|FILE_WRITE_DATA)