#pragma once

#include "common/log.h"
#include "rule.h"
#include "wfp.h"
#include <ntddk.h>

#define DRIVER_OBJECT_DEVICE_NAME L"\\Device\\wfp_demo"

#define DRIVER_OBJECT_SYM_NAME L"\\DosDevices\\wfp_demo"

#define ADD_RULE CTL_CODE(FILE_DEVICE_UNKNOWN, 0x801, METHOD_BUFFERED, FILE_READ_DATA|FILE_WRITE_DATA)

#define CLEAR_RULE_LIST CTL_CODE(FILE_DEVICE_UNKNOWN, 0x802, METHOD_BUFFERED, FILE_READ_DATA|FILE_WRITE_DATA)

#define GET_RULE_LIST CTL_CODE(FILE_DEVICE_UNKNOWN, 0x803, METHOD_BUFFERED, FILE_READ_DATA|FILE_WRITE_DATA)

#define BUFFER_SIZE 1024