#pragma once

#include <Windows.h>
#include <iostream>
#include <string>

#define DRIVER_OBJECT_SYM_NAME "\\\\.\\object_device"

#define IOCTL_OBJECT_TEST_REFLECT CTL_CODE(FILE_DEVICE_UNKNOWN, 0x801, METHOD_BUFFERED, FILE_READ_DATA|FILE_WRITE_DATA)

#define IOCTL_OBJECT_TEST_READ CTL_CODE(FILE_DEVICE_UNKNOWN, 0x802, METHOD_BUFFERED, FILE_READ_DATA|FILE_WRITE_DATA)